CREATE TABLE autores
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_autor VARCHAR(60)                             NOT NULL,
    nacionalidad VARCHAR(60)                             NOT NULL,
    fechaNac     date,
    CONSTRAINT pk_autores PRIMARY KEY (id)
);

CREATE TABLE categorias
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_categoria VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_categorias PRIMARY KEY (id)
);

CREATE TABLE libros
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo       VARCHAR(150)                            NOT NULL,
    anioPub      INTEGER                                 NOT NULL,
    autor_id     BIGINT,
    categoria_id BIGINT,
    CONSTRAINT pk_libros PRIMARY KEY (id)
);

ALTER TABLE libros
    ADD CONSTRAINT FK_LIBROS_ON_AUTOR FOREIGN KEY (autor_id) REFERENCES autores (id);

ALTER TABLE libros
    ADD CONSTRAINT FK_LIBROS_ON_CATEGORIA FOREIGN KEY (categoria_id) REFERENCES categorias (id);